Use 'chart_folder_path' when cleaning up chart output.
zbrookle/avionix pull request #57
Opened 2021-01-05 01:53 UTC by JoshDrake-minted

The current behavior ignores the `output_directory` provided to the chart builder and is potentially dangerous in that it deletes unrelated directory trees!

2021-01-05 05:09 UTC, JoshDrake-minted commented
Leaving a note for working around this, since it's a bit tricky due to all the name mangling going on:

```python
# workaround for https://github.com/zbrookle/avionix/pull/58
def patched_delete_chart_directory(self):
    if os.path.exists(self.chart_folder_path):
        shutil.rmtree(self.chart_folder_path)
ChartBuilder._ChartBuilder__delete_chart_directory = patched_delete_chart_directory

```

2021-01-14 16:03 UTC, zbrookle commented
@JoshDrake-minted Thanks for catching that! Can you add a unit test, to ensure that this feature remains correct?

2021-01-14 16:05 UTC, zbrookle commented
@JoshDrake-minted In terms of the name mangling, that particular class isn't meant to be subclassed, and I can't really provide any guidance on what might happen if it is. Methods that I name mangled were intended to remain private, that's all

2021-01-16 00:23 UTC, zbrookle requested changes
Please add a unit test for this. Thanks!

2021-12-04 04:44 UTC, merged